name: CI

on:
  push:
    branches:
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and run Docker Compose
        run: |
          docker-compose up --build -d selenoid
          docker-compose run tests
          docker-compose down

      - name: Generate Allure Report
        if: always()  # Выполняется даже при ошибках
        run: |
          docker-compose run tests allure generate /app/allure-results -o /app/allure-report --clean
          cp -r allure-report allure-results/history

      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

    env:
      DOCKER_BUILDKIT: 1
